In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
print("tensorflow version:", tf.__version__)   

tensorflow version: 2.19.0


In [2]:
x = tf.constant([[1,2,3], [2,4,5], [1,1,2]])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 4, 5],
       [1, 1, 2]])>

In [14]:
x = tf.ones((3,3))
a = tf.zeros((3, 3))
x, a

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>)

In [30]:
x = tf.random.normal((3, 3, 3), mean=0, stddev=1) #ham random
x = tf.random.uniform((1, 3), minval=1, maxval=10)
x = tf.range(1, 10, 2)
x = tf.cast(x, dtype=tf.bool)   #ep kieu
x

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True,  True,  True,  True,  True])>

In [3]:
x = tf.constant([[3,2,1], [3,2,1], [4, 2, 1]])
y = tf.constant([[3,9,1], [8,3,5], [5,6,2]])

z = tf.add(x, y) # z = x + y
z

z = tf.subtract(x, y) #z = x - y
z

z = tf.divide(x, y) #z = x/y
z

z = tf.multiply(x, y) # z = x * y
z

z = tf.tensordot(x, y, axes = 1) # nhan tung phan tu roi tinh tong
z

x = tf.random.normal((2,3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y) # z = x @ y
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-3.0434299 ,  1.7629153 ,  0.39404327, -1.2850295 ],
       [ 3.6853545 , -1.7333766 ,  0.5458632 ,  0.6893347 ]],
      dtype=float32)>